### ISSUE TITLE
Percent decode is performed too early

### ISSUE THREAD

**Issue by kardeiz** [samscott89/serde_qs#10]
It looks like the percent decoding of the querystring/body is happening too early. Specifically, ampersands that are encoded in the querystring are being decoded and then treated as a field separator.

For example, this QS:

    "markdown=This+%26+that"

Should be deserialized to something like:

    { "markdown: "This & that" }

But is actually deserialized to something like:

    { "markdown": "This ", "that": null }

(I'm just guessing on this last part; in my application I'm deserializing to a struct so the stuff after the ampersand just gets discarded.)

I can look into this more tomorrow unless you have a quick fix.

**Comment by samscott89** [comment]
Again, thanks for reporting this issue. Resulted in a nice little refactor. Those allocations were bothering me from the very beginning.
