### ISSUE TITLE
Can't deserialize some cases when using #[serde(flatten)]

### ISSUE THREAD

**Issue by kardeiz** [samscott89/serde_qs#14]
Hi! When using serde's relatively new `#[serde(flatten)]` feature, nested values are sometimes not parsed correctly. It seems like values that have to be parsed from strings (e.g., numbers) are failing; it seems like they are deserialized too early into a string, rather than the final value type.

For example, here is a failing test

```rust
#[test]
fn flattened_struct() {
    #[derive(Debug,Serialize,Deserialize,PartialEq)]
    struct InnerQuery {
        name: String,
        age: u32
    }

    #[derive(Debug,Serialize,Deserialize,PartialEq)]
    struct Query {
        #[serde(flatten)]
        inner: InnerQuery,
    }

    let query = Query {
        inner: InnerQuery {
            name: "Carrot".into(),
            age: 45
        }
    };

    let params = "name=Carrot&age=45";

    let rec_params: Query = qs::from_str(params).unwrap();

    assert_eq!(rec_params, query);
}
```

This panics with `"invalid type: string \"45\", expected u32"`.

Have you encountered this? Any thoughts or workarounds?

**Comment by kardeiz** [comment]
Nevermind, this appears to be a problem higher up: https://github.com/serde-rs/serde/issues/1183 and https://github.com/nox/serde_urlencoded/issues/33. Closing.

**Comment by samscott89** [comment]
Happened to come across this again today, and proposed [this workaround](https://docs.rs/serde_qs/0.4.4/serde_qs/#flatten-workaround). Leaving here for future interest.

**Comment by maxcountryman** [comment]
> Happened to come across this again today, and proposed [this workaround](https://docs.rs/serde_qs/0.4.4/serde_qs/#flatten-workaround). Leaving here for future interest.

Very helpful--thank you! I wonder if it isn't better to suggest [the `serde_with` crate](https://github.com/serde-rs/serde/issues/1183#issuecomment-668324535) as an alternative to rolling your own `fromstr`?

**Comment by samscott89** [comment]
> 
> 
> > Happened to come across this again today, and proposed [this workaround](https://docs.rs/serde_qs/0.4.4/serde_qs/#flatten-workaround). Leaving here for future interest.
> 
> Very helpful--thank you! I wonder if it isn't better to suggest [the `serde_with` crate](https://github.com/serde-rs/serde/issues/1183#issuecomment-668324535) as an alternative to rolling your own `fromstr`?

Thanks for the suggestion, yes that looks like a better approach!
