### ISSUE TITLE
Newer actix-web versions support

### ISSUE THREAD

**Issue by daddinuz** [samscott89/serde_qs#19]
As in the title, would be cool to support newer releases of actix-web.
The latest release should be v1.0.0-alpha6.

**Comment by samscott89** [comment]
Hey.

Thanks for opening the issue. I would happily accept a PR to add compatibility with v1.0 (perhaps under a new feature, to keep 0.x compatibility), but would probably prefer to keep it in an unreleased git branch until it moves out of alpha/beta. Once it releases I could include it, and might write a quick impl myself.

The newer trait actually looks a lot cleaner (abstracting the config part away), so an implementation should be fairly straightforward.

**Comment by daddinuz** [comment]
Hi @samscott89, finally actix-web v1.0 has been released :rocket:

**Comment by samscott89** [comment]
Thank you for doing that. Merged + version bumped.

**Comment by daddinuz** [comment]
Thank you for your consideration :+1:
