### ISSUE TITLE
serialize_bytes serializes as base64 instead of %-escaped string

### ISSUE THREAD

**Issue by faulesocke** [samscott89/serde_qs#40]
Serializing a byte sequence should really yield a %-escaped string and not a base64 encoded string. This is really surprising and unintuitive.

For example the value `b" "` should become `"%20"` but instead gets serialized to `"IA=="`.

**Comment by samscott89** [comment]
Hey @faulesocke.

Thanks for opening an issue. You're right, that's not correct behaviour, and doesn't match the deserialization logic either. Will push a fix!

**Comment by samscott89** [comment]
Out of interest. What are you using in order to hit the `serialize_bytes` code path? Are you using something like `serde_bytes`?

**Comment by samscott89** [comment]
Fixed in v0.8.1

**Comment by samscott89** [comment]
Thanks again for reporting!
