### ISSUE TITLE
What's the minimum supported Rust version?

### ISSUE THREAD

**Issue by vityafx** [samscott89/serde_qs#42]
Hi! I have received a PR today into [serde aux](https://github.com/vityafx/serde-aux/pull/10).
This PR brings `serde_qs` as a dev-dependency to the project. The minimal rustc version I had was 1.31.1 which I agree, might be old as of now already. But then I decided to use more or less a version of 1.36 where the problem I had encountered before (local objects inside const fns) became stabilised, I now have another [problem](https://travis-ci.org/github/vityafx/serde-aux/jobs/750190572):

```rust
error: enum variants on type aliases are experimental
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_qs-0.8.1/src/error.rs:44:9
   |
44 |         Self::Custom(format!(
   |         ^^^^^^^^^^^^
error: enum variants on type aliases are experimental
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_qs-0.8.1/src/error.rs:56:9
   |
56 |         Self::Parse(msg.to_string(), position)
   |         ^^^^^^^^^^^
error: enum variants on type aliases are experimental
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_qs-0.8.1/src/error.rs:65:9
   |
65 |         Self::Custom(msg.to_string())
   |         ^^^^^^^^^^^^
error: enum variants on type aliases are experimental
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_qs-0.8.1/src/ser.rs:170:9
    |
170 |         Self::Custom(msg.into())
    |         ^^^^^^^^^^^^
```

That said, can you please state what is the minimum supported version of rust the `serde_qs` can be used with? Thanks.

**Comment by samscott89** [comment]
Hey @vityafx!

Thanks for bringing this up. I'm making the MSRV 1.36 for now. I just pushed 0.8.2 which removes the unsupported syntax and added 1.36 to the CI build to keep it checked. Does that work for you?

**Comment by vityafx** [comment]
Hey @samscott89!

Yes, that should work! Let me please check my CI as well :)
