### ISSUE TITLE
Consider not utf-validating fields which are unused.

### ISSUE THREAD

**Issue by Fishrock123** [samscott89/serde_qs#43]
So apparently `serde_qs` still parses and validates the utf-8 of fields that are not in the struct it is attempting to parse to. I think it probably shouldn't.

My issue is ultimately that PayPal is feeding me an invalidly urlencoded `ü` (u with an umlaut), as `%FC` rather than `%C3%BC`.

_However_... it is in a query string field [that I am not even using in my structure](https://github.com/squamishaccess/squamishaccess-signup-function-rs/blob/2bf6a99c7c5337601ad07a01466ef9e7dbde80fd/src/ipn_handler.rs#L14-L25) (It is in `address_street`). I do not think that `serde_qs` should fail in this case.

The output is along the lines of `"invalid utf-8 sequence of 1 bytes from index 4"`.

When parsed via Node.js's [`querystring.decode()`](https://nodejs.org/dist/latest-v15.x/docs/api/querystring.html#querystring_querystring_decode), it shows up as an unknown utf-8 character, rather than failing to parse.

**Comment by samscott89** [comment]
Hey @Fishrock123. That's a great suggestion. I can do a few things:

1. Be more lenient with decoding errors in characters
2. Collect errors but only report them if that field shows up in deserialization

The latter would be a great improvement. You could even report for which key the invalid value as found.

**Comment by Fishrock123** [comment]
I agree that 2. would be very nice!

**Comment by Fishrock123** [comment]
I have a simpler suggestion here - perhaps non-strict mode can ignore faultily encoded characters and just spit them out as the unicode "unknown character" character?

**Comment by Fishrock123** [comment]
Fixed by https://github.com/samscott89/serde_qs/pull/62 in 0.10.0 - thanks!
