### ISSUE TITLE
Publish 0.1.0 to crates.io

### ISSUE THREAD

**Issue by Xion** [samscott89/serde_qs#5]
The README tells to put `serde_qs = "0.1.0"` in the Cargo.toml but the 0.1.0 version isn't available on crates.io. (Using direct Git URL as a workaround works).

**Comment by samscott89** [comment]
Sorry, I was a little hasty with updating the version in the readme. Will publish this after merging #4.

**Comment by samscott89** [comment]
Okay, 0.1.0 is up.
