### ISSUE TITLE
Warp filter doesn't work with repeated fields

### ISSUE THREAD

**Issue by dnaka91** [samscott89/serde_qs#50]
As I saw it was already discussed in #35 that one can use `[]` as suffix for a field to allow to deserialize mulitple values into a `Vec` (or `HashSet` in my case).

This works fine in local tests where I try to deserialize a string like:
```txt
setting[]=a&setting[]=b
```

I wanted to use this through the `warp` framework and always get the `Multiple values for one key` then. After looking at the actual query from the request logs, I saw that the `[` and `]` are encoded, so the above sample becomes:
```txt
setting%5B%5D=a&setting%5B%5D=b
```

Not sure whether this happens on warp side or is auto-converted by the browser (Firefox).

It seems it's either needed to url-decode the string first or check for the encoded form as well. The latter seems like a hack as many other values may be url-encoded and cause wrong deserialization as well.

**Comment by samscott89** [comment]
Hey @dnaka91 !

> Not sure whether this happens on warp side or is auto-converted by the browser (Firefox).

I think it's happening on the browser side. We had a similar conversation here #21 .

To support this, you can set the configuration to non-strict mode. See this warp test for example:

https://github.com/samscott89/serde_qs/blob/main/tests/test_warp.rs#L89-L91

```rust
        let filter = qs::warp::query::<Query>(QsConfig::new(5, false));
```

**Comment by samscott89** [comment]
Let me know if that fixes it

**Comment by dnaka91** [comment]
Hey, sorry for the late reply. I finally got to test it out with the non-strict mode. Sorry btw, I should have read the docs more carefully as they clearly mention the bracket problem.

After using `serde_qs::Config::new(2, false)` it works just fine. Thanks for the quick help and sorry for the trouble.

**Comment by samscott89** [comment]
> 
> 
> Hey, sorry for the late reply. I finally got to test it out with the non-strict mode. Sorry btw, I should have read the docs more carefully as they clearly mention the bracket problem.
> 
> After using `serde_qs::Config::new(2, false)` it works just fine. Thanks for the quick help and sorry for the trouble.

No problem! I remember it confusing me the first time I encountered it in that other thread. It's a subtle one :)
