### ISSUE TITLE
QsString for Actix is not working correctly when using url encoded parameters

### ISSUE THREAD

**Issue by tengkuizdihar** [samscott89/serde_qs#54]
Just as a preamble, I love this library and I'm using it right now for nested parameter query. It's very nice to be used. Also, mind you that I have no idea whether this is a non-goal or an actual bug, but I'm going to make this issue either way just to be sure.

## Issue

I've found a behavior where `QsQuery<T>` behaves oddly when the url is encoded using the methods described in https://en.wikipedia.org/wiki/Percent-encoding. 

For example, this handler and their structs,

```rust
#[derive(Debug, PartialEq, Deserialize, Serialize)]
pub struct QueryTest {
    reg_int: Option<i64>,
    reg_string: Option<String>,
}

#[derive(Debug, Deserialize, Serialize, Clone)]
pub struct FlatParam {
    pub text: Option<String>,
    pub number: Option<i32>,
}

#[get("/test/nested-parameter")]
pub async fn nested_parameter(param: QsQuery<NestedParam>) -> impl Responder {
    actix_web::HttpResponse::Ok().json(param.into_inner())
}
```

If given we give request it using the query parameters,

```
/test/nested-parameter?text=yes&nested%5Btext%5D=very%20nice%20yeah%20%F0%9F%98%8B&nested%5Bnumber%5D=123
```

which is below when decoded,

```
/test/nested-parameter?text=yes&nested[text]=very nice yeah 😋&nested[number]=123
```

will give the response,

```json
{
  "text": "yes",
  "nested": null
}
```

I've also tested the behavior of using `QsParam` using `dbg!()` and it still lead to the same behavior. It seems that the QsString only take a decoded string by design? I've tested `QsString` using a unit test and `TestRequest` and as I've stated, it only works with an already decoded string. I see this as a bug because as far as I've tested, [Insomnia](https://insomnia.rest/download)  and [Axios](https://github.com/axios/axios) encode their parameter using percent encoding.

## Current Workaround

Below is my workaround that I've used in my project. Note that `GeneralResult` is just a wrapper for `Result<T,E>` in my application that uses a custom error that's render-able to the user.

```rust
#[derive(PartialEq, Eq, PartialOrd, Ord)]
pub struct NestedQuery<T>(pub T);

impl<T> NestedQuery<T> {
    /// Get query parameters from the path
    pub fn from_query<S>(query_str: S) -> GeneralResult<T>
    where
        T: de::DeserializeOwned,
        S: AsRef<str>,
    {
        serde_qs::from_str(query_str.as_ref()).map_err(GeneralError::QueryStringParse)
    }
}

impl<T> FromRequest for NestedQuery<T>
where
    T: de::DeserializeOwned,
{
    type Error = GeneralError;

    type Future = Ready<GeneralResult<Self>>;

    type Config = ();

    #[inline]
    fn from_request(req: &actix_web::HttpRequest, _: &mut actix_web::dev::Payload) -> Self::Future {
        let query = match urlencoding::decode(req.query_string()) {
            Ok(a) => a,
            Err(e) => return err(GeneralError::QueryStringParse(serde_qs::Error::FromUtf8(e))),
        };

        let parsed = match Self::from_query(query) {
            Ok(p) => p,
            Err(e) => return err(e),
        };

        ok(Self(parsed))
    }
}
```

## Conclusion

If this is a bug that needed to be addressed, I'm more than happy to work on it. If not, well that's ok too. Thank you for the very useful library, I hope to hear from other contributors soon.

**Comment by samscott89** [comment]
Hey @tengkuizdihar!

Currently, serde_qs defaults to using "strict" mode. In which we expect non-percent encoded square brackets to represent any nested keys. You can change this behaviour by setting the configuration flag: https://docs.rs/serde_qs/0.8.5/serde_qs/#strict-vs-non-strict-modes
