### ISSUE TITLE
Unnamed keys don't work with strict mode?

### ISSUE THREAD

**Issue by kevincox** [samscott89/serde_qs#55]
I was surprised to find that `foo[]=a&foo[]=b` into a `Vec<String>` fails in strict mode with `Multiple values for one key`. The docs describe strict mode as being about encoding only but it seems to also affect the behaviour of un-encoded insertions with implicit numbering. 

Would it be possible to remove this limitation so that I can benefit from both implicit numbering and strict mode?

**Comment by jalcine** [comment]
Did you determine that strictness application in the code itself (if so, do you mind linking)?

**Comment by jalcine** [comment]
Looking at https://github.com/samscott89/serde_qs/blob/main/src/de/parse.rs#L289-L304, it _looks_ like it should allow something like `foo[]=a&foo[]=b`

**Comment by kevincox** [comment]
Hmm, this seems to have been fixed since I filed the issue? Or I was somehow mistaken when originally testing. The following now works.

```rust
#[test]
fn test() {
	#[derive(Debug,PartialEq,serde::Deserialize)]
	pub struct Query {
		pub strings: Vec<String>,
	}

	let q: Query = serde_qs::Config::new(2, true)
		.deserialize_str("strings[]=foo&strings[]=bar")
		.unwrap();

	assert_eq!(q, Query{strings: vec!["foo".to_string(), "bar".to_string()]})
}
```

**Comment by kevincox** [comment]
Ah, the bug was on my end. I was using this for `application/x-www-form-urlencoded` from a browser form and it appears that the browser does encode the `[]` so it does make sense to use non-strict mode in this scenario. I'll need to check my other application where I hit this first a while back and see why it is using non-strict. But either way it seems that today this problem doesn't exist.

**Comment by samscott89** [comment]
Nice, thanks for following up @kevincox + @jalcine!

A bunch of people have hit this problem since it's not always obvious what the browser will do. 

I could imagine a relatively simple addition being: when in strict mode, check if the keys that clash contain square brackets and return a little more information. What do you think?

**Comment by kevincox** [comment]
Yeah, that would be a great benefit to user experience. If you also highlight that the brackets were encoded it would make it really obvious what is happening.

**Comment by samscott89** [comment]
Cool, adding this to 0.9.1.
Error message should look like:

```
Multiple values for one key: "vec%5B%5D"
Invalid field contains an encoded bracket -- did you mean to use non-strict mode?
  https://docs.rs/serde_qs/latest/serde_qs/#strict-vs-non-strict-modes
```
