### ISSUE TITLE
Do not force UTF-8 validation / option to prevent % decoding

### ISSUE THREAD

**Issue by ckcr4lyf** [samscott89/serde_qs#58]
I am writing a bittorrent tracker, and it is common for clients to encode the raw bytes for a request as percent encoded values. Example:

```
GET /blahblah?param=%c3ABCD
```
If it needs to send the byte `0xc3` , followed by the bytes which _can_ be ASCII encoded (0x65 = A, etc.) . Since this is not valid UTF-8, serde_qs will return an error.

This happens even if I my struct recepient is `Vec<u8>` and not `String`.. I would think at least for the `Vec<u8>` target it does not need to % decode to valid UTF-8.

**Comment by samscott89** [comment]
Hey @ckcr4lyf. That's a great point, I don't think we need to decode the value until the last possible moment!

Would you be up for submitting a PR to address this?

Also, if you're not using nested keys (e.g. `/blahblah?foo[bar]=1`) then you might want to consider trying [serde_urlencoded](https://github.com/nox/serde_urlencoded/) instead. It might handle this case better?

**Comment by samscott89** [comment]
I think the change would be pretty large, but mostly straightforward. We would have the leaf nodes (which are the values) store a vec of bytes rather than a string: https://github.com/samscott89/serde_qs/blob/main/src/de/mod.rs#L202

And make sure we collect into a vec instead of a string, and propagate that change all the way through

**Comment by ckcr4lyf** [comment]
Thanks for the reply. While checking out the serde_urlencoded crate I noticed a similar issue was raised which I followed up on (https://github.com/nox/serde_urlencoded/issues/98) , it seems to perhaps originate at an even higher level - the rust-url library (https://github.com/servo/rust-url/).

I am not too familiar with "advanced" Rust yet, are you suggesting that this can be solved at this library level, or it comes in due to how `rust-url` handled percent decoding?

**Comment by ckcr4lyf** [comment]
From `rust-url` I find this in source: https://github.com/servo/rust-url/blob/master/percent_encoding/src/lib.rs#L346

Not sure how relevant it is, but seems it will percent decode into `u8` rather than attempt `UTF-8` string, so maybe that is not the issue?

**Comment by ckcr4lyf** [comment]
Actually, it seems the decoding in the parent lib (rust-url) parsing UTF-8 is intentional. The library mentions: "Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986" , which further states: 

```
A legacy server-oriented implementation might have to support [encodings](https://encoding.spec.whatwg.org/#encoding) other than [UTF-8](https://encoding.spec.whatwg.org/#utf-8) as well as have special logic for tuples of which the name is `_charset`. Such logic is not described here as only [UTF-8](https://encoding.spec.whatwg.org/#utf-8) is conforming.
```

(Ref: https://url.spec.whatwg.org/#urlencoded-parsing)

So I think they will not change it... Instead I will use my current hack to first replace the `%` character with `%25` , so that when I decode raw bytes, it will work as:

1. `%c3A` - input
2. `%25c3A` - replace `%` with `%25`
3. `%c3A` - now the UTF-8 decoded result is the original & encoded string
4. `[0xc3, 0x41` manually parse the %bytes and normal bytes (which I implement here - https://github.com/ckcr4lyf/kiryuu/blob/2536307dd7962737b5804b90b3ad0541c8d9f5ac/src/byte_functions/mod.rs#L9)

Closing this issue since I guess it isn't applicable due to design choice of parent lib...
