### ISSUE TITLE
Instantiating `QsSerializer`

### ISSUE THREAD

**Issue by ticklepoke** [samscott89/serde_qs#63]
Is there support for instantiating `QsSerializer` like how [serde_json](https://docs.serde.rs/serde_json/struct.Serializer.html) provides a `new()` constructor method?

I intend to use `serde_qs` with [`serde_path_to_error::serialize()`](https://docs.rs/serde_path_to_error/latest/serde_path_to_error/fn.serialize.html) and they require an `impl Serialize` object as an argument.

**Comment by samscott89** [comment]
Hey @ticklepoke! sorry for the slow response here.

This is a super reasonable request. Just added to 0.10: https://docs.rs/serde_qs/latest/serde_qs/struct.Serializer.html

**Comment by arlyon** [comment]
Wow thanks for sorting this out! :heart:
