### ISSUE TITLE
Sequence of structs doesn't work with 0.2

### ISSUE THREAD

**Issue by Xion** [samscott89/serde_qs#7]
I'm afraid it's me again. The repro is extremely simple this time, though:
```rust
             extern crate serde;
#[macro_use] extern crate serde_derive;
#[macro_use] extern crate serde_json;
             extern crate serde_qs;  // either 0.2 or HEAD as of this writing


#[derive(Deserialize, Debug)]
struct TestStruct {
    v: String,
}

#[derive(Deserialize, Debug)]
struct NestedStruct {
    ts: Vec<TestStruct>,
}


fn main() {
    println!("serde_json: {:?}", serde_json::from_str::<NestedStruct>(&json!({
        "ts": [{"v": "foo"}, {"v": "bar"}],
    }).to_string()));
    println!("serde_qs: {:?}", serde_qs::from_str::<NestedStruct>(
        "ts[0][v]=foo&ts[1][v]=bar"
    ));
}
```

This gives:
```
serde_json: Ok(NestedStruct { ts: [TestStruct { v: "foo" }, TestStruct { v: "bar" }] })
serde_qs: Err(Error(Custom("invalid type: map, expected a sequence"), State { next_error: None, backtrace: None }))
```

Seems directly related to the recent changes to handling indexed sequences. The last revision without this bug is 071affd963ed88bfdcede6aa7b20626d3cf0f368; it occurs on 6f22cff63ad58c722293f8d74c978a0bf616be67 and beyond (including 0.2 on crates.io).

**Comment by samscott89** [comment]
Yup, good spot. Missed creating the correct type of map when dropping down a level.
Thanks again! These are super useful.
Actually, I'm going to open an issue to get some code coverage so I can make sure I'm getting these corner cases.
